name: membrane
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.4.5.2
  - certifi=2020.4.5.2
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.4
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  # - libgfortran=3.0.1
  - libsodium=1.0.16
  - llvm-openmp=10.0.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - portaudio=19.6.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pyaudio=0.2.11
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pyzmq=18.1.1
  - readline=8.0
  - requests=2.23.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=47.1.1
  - six=1.15.0
  - speechrecognition=3.6.3
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - tqdm=4.46.1
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - audioread==2.1.8
    - librosa==0.7.2
    - llvmlite==0.31.0
    - numba==0.48.0
    - resampy==0.2.2
    - soundfile==0.10.3.post1

